"""Initial schema with all 7 models

Revision ID: afdcfcbfd9ab
Revises: 
Create Date: 2025-10-25 13:10:42.673714+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdcfcbfd9ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('posted_to_channel', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('generation_duration_seconds', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('generated', 'posted', 'failed', name='image_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_images_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_images_status'), ['status'], unique=False)

    op.create_table('scheduled_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.Enum('random_dm', 'image_post', 'cleanup', 'reminder', name='task_type_enum'), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'channel', 'system', name='target_type_enum'), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'executing', 'completed', 'failed', 'cancelled', name='task_status_enum'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slack_user_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('real_name', sa.String(length=150), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_proactive_dm_at', sa.DateTime(), nullable=True),
    sa.Column('total_messages_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_last_proactive_dm_at'), ['last_proactive_dm_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_slack_user_id'), ['slack_user_id'], unique=True)

    op.create_table('configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'integer', 'float', 'boolean', 'json', name='value_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurations_key'), ['key'], unique=True)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_member_id', sa.String(length=36), nullable=False),
    sa.Column('channel_type', sa.Enum('dm', 'channel', 'thread', name='channel_type_enum'), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('thread_ts', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_team_member_id'), ['team_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_thread_ts'), ['thread_ts'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.Enum('user', 'bot', name='sender_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('slack_ts', sa.String(length=50), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_slack_ts'), ['slack_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    op.create_table('engagement_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('thread_ts', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.Enum('thread_response', 'reaction', 'ignored', name='event_type_enum'), nullable=False),
    sa.Column('decision_probability', sa.Float(), nullable=False),
    sa.Column('random_value', sa.Float(), nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagement_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_events_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_engaged'), ['engaged'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_thread_ts'), ['thread_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagement_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_thread_ts'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_engaged'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_channel_id'))

    op.drop_table('engagement_events')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_slack_ts'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_thread_ts'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_team_member_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_is_active'))

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_key'))

    op.drop_table('configurations')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_slack_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_last_proactive_dm_at'))
        batch_op.drop_index(batch_op.f('ix_team_members_is_admin'))
        batch_op.drop_index(batch_op.f('ix_team_members_is_active'))

    op.drop_table('team_members')
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_job_id'))

    op.drop_table('scheduled_tasks')
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_images_status'))
        batch_op.drop_index(batch_op.f('ix_generated_images_posted_at'))

    op.drop_table('generated_images')
    # ### end Alembic commands ###
