<template>
  <div class="images-gallery">
    <div class="page-header">
      <h2>Generated Images</h2>
      <p class="page-description">View all images generated by Lukas</p>
    </div>

    <div class="filters-section">
      <div class="filters-grid">
        <div class="filter-group">
          <label for="start-date">Start Date</label>
          <input
            id="start-date"
            v-model="filters.start_date"
            type="datetime-local"
            class="filter-input"
          />
        </div>

        <div class="filter-group">
          <label for="end-date">End Date</label>
          <input
            id="end-date"
            v-model="filters.end_date"
            type="datetime-local"
            class="filter-input"
          />
        </div>

        <div class="filter-group">
          <label for="status">Status</label>
          <select
            id="status"
            v-model="filters.status"
            class="filter-input"
          >
            <option value="">All Statuses</option>
            <option value="pending">Pending</option>
            <option value="posted">Posted</option>
            <option value="failed">Failed</option>
          </select>
        </div>
      </div>

      <div class="filters-actions">
        <button @click="applyFilters" class="btn btn-primary">
          Apply Filters
        </button>
        <button @click="clearFilters" class="btn btn-secondary">
          Clear Filters
        </button>
      </div>
    </div>

    <div v-if="loading && items.length === 0" class="loading-state">
      <div class="spinner"></div>
      <p>Loading images...</p>
    </div>

    <div v-else-if="error" class="error-state">
      <p class="error-message">{{ error }}</p>
      <button @click="fetchImages" class="btn btn-secondary">Retry</button>
    </div>

    <div v-else-if="items.length === 0" class="empty-state">
      <p>No images found</p>
      <p class="empty-hint">Try adjusting your filters or date range</p>
    </div>

    <div v-else class="gallery-grid">
      <ImageCard
        v-for="image in items"
        :key="image.id"
        :image="image"
        @click="openImageDetail(image)"
      />
    </div>

    <Pagination
      v-if="items.length > 0"
      :current-page="currentPage"
      :total-pages="totalPages"
      :total="total"
      :limit="limit"
      :start-item="startItem"
      :end-item="endItem"
      :has-next-page="hasNextPage"
      :has-prev-page="hasPrevPage"
      @next="handleNextPage"
      @prev="handlePrevPage"
      @goto="handleGoToPage"
      @change-limit="handleChangeLimit"
    />

    <!-- Image Detail Modal -->
    <div v-if="selectedImage" class="modal-overlay" @click="closeImageDetail">
      <div class="modal-content" @click.stop>
        <button class="modal-close" @click="closeImageDetail">×</button>

        <div class="modal-body">
          <div class="modal-image-container">
            <img
              v-if="selectedImage.id"
              :src="`/api/images/${selectedImage.id}/full`"
              :alt="selectedImage.prompt"
              class="modal-image"
              @error="onModalImageError"
            />
            <div v-else class="no-image">
              <span>Image not available</span>
            </div>
          </div>

          <div class="modal-details">
            <h3>Image Details</h3>

            <div class="detail-section">
              <h4>Prompt</h4>
              <p class="prompt-full">{{ selectedImage.prompt }}</p>
            </div>

            <div class="detail-section">
              <h4>Metadata</h4>
              <div class="metadata-grid">
                <div class="metadata-item">
                  <span class="metadata-label">Status:</span>
                  <span :class="['metadata-value', `status-${selectedImage.status}`]">
                    {{ selectedImage.status }}
                  </span>
                </div>
                <div class="metadata-item">
                  <span class="metadata-label">Created:</span>
                  <span class="metadata-value">{{ formatDate(selectedImage.created_at) }}</span>
                </div>
                <div v-if="selectedImage.posted_at" class="metadata-item">
                  <span class="metadata-label">Posted:</span>
                  <span class="metadata-value">{{ formatDate(selectedImage.posted_at) }}</span>
                </div>
                <div v-if="selectedImage.channel_id" class="metadata-item">
                  <span class="metadata-label">Channel:</span>
                  <span class="metadata-value">{{ selectedImage.channel_id }}</span>
                </div>
              </div>
            </div>

            <div v-if="selectedImage.error_message" class="detail-section">
              <h4>Error Message</h4>
              <p class="error-details">{{ selectedImage.error_message }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, watch } from 'vue'
import { getImages, getImageDetail } from '../services/images'
import { usePagination } from '../composables/usePagination'
import { formatDate } from '../utils/date'
import ImageCard from '../components/ImageCard.vue'
import Pagination from '../components/Pagination.vue'

export default {
  name: 'ImagesGallery',
  components: {
    ImageCard,
    Pagination
  },
  setup() {
    // State
    const items = ref([])
    const loading = ref(false)
    const error = ref('')
    const selectedImage = ref(null)

    // Filters
    const filters = ref({
      start_date: '',
      end_date: '',
      status: ''
    })

    const appliedFilters = ref({})

    // Pagination
    const {
      currentPage,
      limit,
      total,
      totalPages,
      hasNextPage,
      hasPrevPage,
      startItem,
      endItem,
      updatePagination,
      nextPage,
      prevPage,
      goToPage,
      changeLimit,
      reset: resetPagination
    } = usePagination(1, 20)

    // Fetch images
    async function fetchImages() {
      loading.value = true
      error.value = ''

      try {
        const params = {
          page: currentPage.value,
          limit: limit.value,
          ...appliedFilters.value
        }

        const response = await getImages(params)
        items.value = response.items || []
        updatePagination(response)
      } catch (err) {
        error.value = err.message || 'Failed to load images'
        items.value = []
      } finally {
        loading.value = false
      }
    }

    // Apply filters
    function applyFilters() {
      const formatted = {}
      if (filters.value.start_date) {
        formatted.start_date = new Date(filters.value.start_date).toISOString()
      }
      if (filters.value.end_date) {
        formatted.end_date = new Date(filters.value.end_date).toISOString()
      }
      if (filters.value.status) {
        formatted.status = filters.value.status
      }

      appliedFilters.value = formatted
      resetPagination()
      fetchImages()
    }

    // Clear filters
    function clearFilters() {
      filters.value = {
        start_date: '',
        end_date: '',
        status: ''
      }
      appliedFilters.value = {}
      resetPagination()
      fetchImages()
    }

    // Image detail modal
    async function openImageDetail(image) {
      try {
        const details = await getImageDetail(image.id)
        selectedImage.value = details
      } catch (err) {
        error.value = err.message || 'Failed to load image details'
      }
    }

    function closeImageDetail() {
      selectedImage.value = null
    }

    function onModalImageError(event) {
      console.error('Failed to load full-size image:', event)
    }

    // Pagination handlers
    function handleNextPage() {
      nextPage()
    }

    function handlePrevPage() {
      prevPage()
    }

    function handleGoToPage(page) {
      goToPage(page)
    }

    function handleChangeLimit(newLimit) {
      changeLimit(newLimit)
    }

    // Watch for pagination changes
    watch([currentPage, limit], () => {
      fetchImages()
    })

    // Initial load
    fetchImages()

    return {
      items,
      loading,
      error,
      selectedImage,
      filters,
      applyFilters,
      clearFilters,
      currentPage,
      limit,
      total,
      totalPages,
      hasNextPage,
      hasPrevPage,
      startItem,
      endItem,
      handleNextPage,
      handlePrevPage,
      handleGoToPage,
      handleChangeLimit,
      fetchImages,
      openImageDetail,
      closeImageDetail,
      onModalImageError,
      formatDate
    }
  }
}
</script>

<style scoped>
.images-gallery {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.page-header {
  background: white;
  padding: 24px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.page-header h2 {
  margin: 0 0 8px 0;
  font-size: 24px;
  color: #333;
}

.page-description {
  margin: 0;
  color: #666;
  font-size: 14px;
}

.filters-section {
  background: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.filters-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 16px;
  margin-bottom: 16px;
}

.filter-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.filter-group label {
  font-size: 13px;
  font-weight: 600;
  color: #555;
}

.filter-input {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  transition: border-color 0.2s;
}

.filter-input:focus {
  outline: none;
  border-color: #667eea;
}

.filters-actions {
  display: flex;
  gap: 12px;
}

/* Loading/Error/Empty States */
.loading-state,
.error-state,
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 20px;
  background: white;
  border-radius: 8px;
  color: #666;
}

.spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #667eea;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 15px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.empty-hint {
  font-size: 14px;
  color: #999;
  margin-top: 5px;
}

/* Gallery Grid */
.gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 20px;
  background: white;
  padding: 20px;
  border-radius: 8px;
}

/* Modal */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.75);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
}

.modal-content {
  background: white;
  border-radius: 12px;
  max-width: 900px;
  width: 100%;
  max-height: 90vh;
  overflow-y: auto;
  position: relative;
}

.modal-close {
  position: absolute;
  top: 16px;
  right: 16px;
  background: rgba(0, 0, 0, 0.5);
  color: white;
  border: none;
  border-radius: 50%;
  width: 32px;
  height: 32px;
  font-size: 24px;
  line-height: 1;
  cursor: pointer;
  z-index: 1;
  transition: background 0.2s;
}

.modal-close:hover {
  background: rgba(0, 0, 0, 0.7);
}

.modal-body {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
  padding: 24px;
}

.modal-image-container {
  background: #f5f5f5;
  border-radius: 8px;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 300px;
}

.modal-image {
  width: 100%;
  height: auto;
  display: block;
}

.no-image {
  padding: 40px;
  color: #999;
  text-align: center;
}

.modal-details h3 {
  margin: 0 0 20px 0;
  font-size: 20px;
  color: #333;
}

.detail-section {
  margin-bottom: 24px;
}

.detail-section:last-child {
  margin-bottom: 0;
}

.detail-section h4 {
  margin: 0 0 12px 0;
  font-size: 14px;
  font-weight: 600;
  color: #555;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.prompt-full {
  margin: 0;
  padding: 12px;
  background: #f8f9fa;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  font-size: 14px;
  line-height: 1.6;
  white-space: pre-wrap;
  word-wrap: break-word;
}

.metadata-grid {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.metadata-item {
  display: flex;
  gap: 8px;
}

.metadata-label {
  font-size: 13px;
  font-weight: 600;
  color: #666;
  min-width: 100px;
}

.metadata-value {
  font-size: 13px;
  color: #333;
}

.metadata-value.status-posted {
  color: #155724;
  font-weight: 600;
}

.metadata-value.status-failed {
  color: #721c24;
  font-weight: 600;
}

.metadata-value.status-pending {
  color: #856404;
  font-weight: 600;
}

.error-details {
  margin: 0;
  padding: 12px;
  background: #fff5f5;
  border: 1px solid #feb2b2;
  border-radius: 4px;
  color: #c53030;
  font-size: 13px;
  line-height: 1.6;
}

@media (max-width: 768px) {
  .modal-body {
    grid-template-columns: 1fr;
  }

  .gallery-grid {
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 12px;
  }

  .filters-grid {
    grid-template-columns: 1fr;
  }
}
</style>
